version: '3'
services:

  salesman-database:
    image: "postgres:9.6-alpine"
    container_name: salesman-database
    volumes:
      - salesman-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=salesman
      - POSTGRES_USER=salesman
      - POSTGRES_PASSWORD=salesman

  salesman-backend:
    build: ./Backend
    container_name: salesman-backend
    environment:
      - DB_SERVER=salesman-database
    ports:
      - 8080:8080
    links:
      - salesman-database

  salesman-prediction:
    build: ./Prediction
    container_name: salesman-prediction
    ports:
      - 8090:8090
    links:
      - salesman-backend

  salesman-frontend:
    build: ./Frontend
    container_name: salesman-frontend
    volumes:
      - salesman-webiste:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    links:
      - salesman-backend

volumes:
  salesman-data:
  salesman-webiste:
